version: 0.2
phases:
  pre_build:
    commands:
      - echo "pre build"
  build:
    commands:
      - echo "building"
  post_build:
    commands:
      - echo "post build"
      - cp -r $CODEBUILD_SRC_DIR $CODEBUILD_MY_EFS
